### ISSUE TITLE
macOS runner support

### ISSUE THREAD

**Issue by HatsuneMiku3939** [HatsuneMiku3939/direnv-action#254]
ref
- https://github.com/retrohacker/getos

**Comment by nmittler** [comment]
I was just trying the out the latest commit and was seeing the error below. Just wanted to confirm that this is the same issue?

```
allowing envrc...
/Users/runner/hostedtoolcache/direnv/2.32.1/x64/direnv allow
Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at ToolRunner.<anonymous> (...)
    at Generator.next (<anonymous>)
    at /Users/runner/work/_actions/HatsuneMiku3939/direnv-action/50946bcbcb4[71](...
    at new Promise (<anonymous>)
    at __webpack_modules__.8159.__awaiter (/Users/runner/work/_actions/HatsuneMiku3939/direnv-action/50946bcbcb47179fcc1cc70d1e2f5f63d4242058/node_modules/@actions/exec/lib/toolrunner.js:23:1)
    at /Users/runner/work/_actions/HatsuneMiku3939/direnv-action/50946bcbcb471[79](...
    at new Promise (<anonymous>)
    at ToolRunner.<anonymous> (/Users/runner/work/_actions/HatsuneMiku3939/direnv-action/50946bcbcb47179fcc1cc70d1e2f5f63d4242058/node_modules/@actions/exec/lib/toolrunner.js:395:1)
```

**Comment by HatsuneMiku3939** [comment]
@nmittler 

Thank you for your report. Yes, you're right; that is the same issue we've been encountering. 
Currently, `direnv-actions` is installing a Linux binary on the OSX runner, which is causing a system error.

**Comment by HatsuneMiku3939** [comment]
@nmittler 

A new version (v1.0.7) was just released. The new version adds support for `linux-x86_64`, `darwin-x86_64`, and `darwin-arm64`. A new feature will affect automatically on `HatsuneMiku3939/direnv-action@v1`.

If new feature dose not resolve this issue, feel free to fork/PR. Any PR are welcome.

**Comment by nmittler** [comment]
@HatsuneMiku3939 v1.0.7 did the trick. Thanks for the patch!

**Comment by nmittler** [comment]
@HatsuneMiku3939 I may have spoken too soon. I have the same workflow running on `ubuntu-latest` and `macos-latest`.  Unbuntu works fine. On mac, the nix install step succeeds, but the next step fails since it can't find `buf` on path (it's defined in flake.nix).

My install nix step is just a composite that consists of:

```
runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@v9
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - uses: HatsuneMiku3939/direnv-action@efeb6682d71f04d458eaff190e0e9bf684417bd1
```

Comparing the logs between unbuntu and osx gives a hint:

```
// ubuntu
...
allowing envrc...
/opt/hostedtoolcache/direnv/2.32.1/x64/direnv allow
exporting envrc...
Received 4717121 of 4717121 (100.0%), 2.2 MBs/sec
detected PATH in .envrc, appending to PATH...
setting masks: 
```

```
// osx
...
allowing envrc...
/Users/runner/hostedtoolcache/direnv/2.32.1/x64/direnv allow
exporting envrc...
setting masks: 
```

So it looks like PATH is not being set up properly for osx.

Any thoughts?

**Comment by HatsuneMiku3939** [comment]
@nmittler 
Can you please share your `.envrc` or any information that would allow me to reproduce it? 

In my test case(`v2.32.3` on `darwin-x64`), `PATH` variable was exported.

```
installing direnv-2.32.3 on darwin-x64
direnv not found in tool-cache, restoring from cache...
Cache Size: ~4 MB (45920[6](https://github.com/HatsuneMiku3939/direnv-action/actions/runs/8062423865/job/22022109756#step:6:7)2 B)
/usr/local/bin/gtar -xf /Users/runner/work/_temp/bea901fd-0cf[7](https://github.com/HatsuneMiku3939/direnv-action/actions/runs/8062423865/job/22022109756#step:6:8)-422f-[8](https://github.com/HatsuneMiku3939/direnv-action/actions/runs/8062423865/job/22022109756#step:6:9)[9](https://github.com/HatsuneMiku3939/direnv-action/actions/runs/8062423865/job/22022109756#step:6:10)ca-6330df2d0b57/cache.tzst -P -C /Users/runner/work/direnv-action/direnv-action --delay-directory-restore --use-compress-program unzstd
Received 4592062 of 4592062 (100.0%), 4.4 MBs/sec
Cache restored successfully
direnv restored from cache, key: hatsunemiku3939-direnv-action-toolcache-2.32.3-darwin-x64
saving to tool-cache...
/bin/rm -rf /Users/runner/work/direnv-action/direnv-action/.direnv-action
allowing envrc...
/Users/runner/hostedtoolcache/direnv/2.32.3/x64/direnv allow
exporting envrc...
detected PATH in .envrc, appending to PATH...
setting masks: SECRET1, SECRET2
```

**Comment by nmittler** [comment]
@HatsuneMiku3939 

Sure thing. The `.envrc` is pretty simple:

```
if ! has nix_direnv_version || ! nix_direnv_version 3.0.4; then
    source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/3.0.4/direnvrc" "sha256-DzlYZ33mWF/Gs8DDeyjr8mnVmQGx7ASYqA5WlxwvBG4="
fi
use flake
```

And our `flake.nix` is pretty simple. Here's the outputs where `buf` is added:

```
  outputs = { nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        devShells.default = pkgs.mkShell {
          packages = with pkgs; [
            buf
            ...
          ];
        ...
      }
    });
}
```

IIUC, the [default systems](https://github.com/numtide/flake-utils?tab=readme-ov-file#defaultsystems--system) should include `x86_64-darwin`.

**Comment by nmittler** [comment]
Hey @HatsuneMiku3939 any updates here?
